services:
  - type: web
    name: gregpedro-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
  - type: web
    name: gregpedro-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
